### ISSUE TITLE
Username Validator

### ISSUE THREAD

**Issue by chrisabruce** [maelstrom-rs/maelstrom#116]
We need to have a function to validate usernames.  A good place to start would be to look at the [Matrix Spec regarding valid usernames](https://matrix.org/docs/spec/appendices#user-identifiers) as well as Synapse or Dendrite's implementation. Synapse: [check_user_registration](https://github.com/matrix-org/synapse/blob/9bae740527c4621f9f8eb8ca936669f2372c42eb/synapse/handlers/register.py#L79)

I possible good place to put this function might be:
https://github.com/maelstrom-rs/maelstrom/blob/master/src/models/registration.rs

**Comment by sparky8251** [comment]
This should be good as of #117. `ruma_identifiers` has build in validation logic, even for "edge cases" like historical names.
