### ISSUE TITLE
Joining project

### ISSUE THREAD

**Issue by zmilan** [maelstrom-rs/maelstrom#127]
@chrisabruce I would like to join this project. Is there something small that I can take first. I'm still at the beginning of my Rust journey and have only small experience using Actix-web and SQLx for building some small test projects... Besides that, I have been professionally programming since 2003 and have lot of experience...

**Comment by chrisabruce** [comment]
Hey great!  There is still a lot of foundational stuff being added.  But a good first commit might be around logout #77 

Happy to help get you through your first commit!

**Comment by zmilan** [comment]
Hi @chrisabruce, thanks. I will do it :)
