### ISSUE TITLE
Question: Since JSON != performance, CBOR ?

### ISSUE THREAD

**Issue by maisiliymBridj** [maelstrom-rs/maelstrom#133]

**Comment by piegamesde** [comment]
The usage of JSON is specified by the Matrix protocol and is not a simple implementation detail. A server that communicates with other encodings is going to be pretty lonely and unable to communicate with anyone else.

From <https://matrix.org/docs/spec/client_server/r0.6.1#api-standards>:

> The mandatory baseline for client-server communication in Matrix is exchanging JSON objects over HTTP APIs. […] More efficient optional transports will in future be supported as optional extensions - e.g. a packed binary encoding over stream-cipher encrypted TCP socket for low-bandwidth/low-roundtrip mobile usage.

**Comment by dr-bonez** [comment]
it would be possible to change behavior based on accept headers. that way we could have the more efficient encoding when a client explicitly supports it. that said if straight performance is what you are looking for, I would recommend a predefined encoding as opposed to a flexible one.

**Comment by maisiliymBridj** [comment]
@dr-bonez is right, of course, but CBOR was suggested on the fact matrix team already experimented with it. Feel free to close, as the author was just curious; always looking for those who use *actual code* for messaging.
