### ISSUE TITLE
Server administration: getWhoami

### ISSUE THREAD

**Issue by chrisabruce** [maelstrom-rs/maelstrom#14]
Gets information about a particular user.

Gets information about a particular user.

This API may be restricted to only be called by the user being looked
up, or by a server admin. Server-local administrator privileges are not
specified in this document.

Here is link to spec: https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-account-whoami

**Comment by mcrakhman** [comment]
Thanks, will start working on the ticket

**Comment by craftytrickster** [comment]
Looks like this is done -> https://github.com/maelstrom-rs/maelstrom/pull/130
